# Generated by Django 4.2.3 on 2023-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_slip', '0002_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_date',
            field=models.DateField(null=True),
        ),
    ]
