# Generated by Django 4.2.3 on 2023-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_slip', '0003_order_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='row_id',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
