# Generated by Django 4.2.3 on 2023-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_slip', '0004_orderitem_row_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
