# Generated by Django 4.2.3 on 2023-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_slip', '0005_alter_order_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
