# Generated by Django 4.2.3 on 2023-08-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('slip_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('crash_credit', models.CharField(max_length=30)),
                ('cost_category', models.CharField(max_length=30)),
                ('factory_code', models.CharField(max_length=30)),
                ('storehouse_code', models.CharField(max_length=30)),
                ('charger_code', models.CharField(max_length=30)),
                ('update_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(default='', max_length=200, null=True)),
                ('product_code', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('product_part_number', models.CharField(max_length=30)),
                ('size_code', models.CharField(max_length=30)),
                ('color_code', models.CharField(max_length=30)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('max_cost', models.FloatField(default=0)),
                ('min_cost', models.FloatField(default=0)),
                ('max_price', models.FloatField(default=0)),
                ('min_price', models.FloatField(default=0)),
                ('other', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_slip.purchase')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
