# Generated by Django 4.2.3 on 2023-08-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_slip', '0004_purchase_dealer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='dealer_code',
        ),
    ]
