# Generated by Django 4.2.3 on 2023-08-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_slip', '0005_remove_purchase_dealer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchaseorder_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
