# Generated by Django 4.2.3 on 2023-09-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder_slip', '0003_remove_purchaseorderitem_color_code_and_more'),
        ('purchase_slip', '0007_remove_purchaseitem_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchaseorder_no',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchaseorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseorder_slip.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchaseorderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseorder_slip.purchaseorderitem'),
        ),
    ]
