# Generated by Django 4.2.3 on 2023-08-24 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('slip_date', models.DateField()),
                ('dealer_code', models.CharField(max_length=30)),
                ('last_payment_date', models.DateField(max_length=30)),
                ('last_payment', models.CharField(max_length=30)),
                ('expected_date', models.DateField()),
                ('remain_payment', models.CharField(max_length=30)),
                ('other', models.CharField(max_length=200)),
                ('update_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(default='', max_length=200, null=True)),
                ('payment_category', models.CharField(max_length=30)),
                ('payment_price', models.CharField(max_length=30)),
                ('payment_date', models.DateField()),
                ('other', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_slip.payment')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
