# Generated by Django 4.2.3 on 2023-08-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='dealer_code',
            new_name='supplier_code',
        ),
    ]
