# Generated by Django 4.2.3 on 2023-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0002_rename_dealer_code_payment_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
