# Generated by Django 4.2.3 on 2023-09-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_slip', '0008_remove_purchase_purchaseorder_no_and_more'),
        ('payment_slip', '0003_payment_purchase_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='purchase_no',
        ),
        migrations.RemoveField(
            model_name='paymentitem',
            name='payment_category',
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_slip.purchase'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='purchaseItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_slip.purchaseitem'),
        ),
    ]
