# Generated by Django 4.2.3 on 2023-08-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_name',
            new_name='name',
        ),
    ]
