# Generated by Django 4.2.3 on 2023-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='phone',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tel',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
