# Generated by Django 4.2.3 on 2023-08-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slip', '0002_orderslip_date_created_orderslip_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderslip',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='orderslip',
            name='status',
            field=models.CharField(choices=[('発注済み', '発注済み'), ('売上転送済み', '売上転送済み'), ('取置転送済み', '取置転送済み')], max_length=10),
        ),
    ]
