# Generated by Django 4.2.3 on 2023-07-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_brand_charger_dealer_delivery_exhibition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingdepartment',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
