# Generated by Django 4.2.3 on 2023-08-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchaseorder_slip', '0002_purchaseorder_other'),
        ('payment_slip', '0002_rename_dealer_code_payment_supplier_code'),
        ('deposit_slip', '0001_initial'),
        ('sale_slip', '0003_sale_dealer_code'),
        ('order_slip', '0006_order_dealer_code'),
        ('purchase_slip', '0005_remove_purchase_dealer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('product_part_number', models.CharField(max_length=30)),
                ('size_code', models.CharField(max_length=30)),
                ('color_code', models.CharField(max_length=30)),
                ('storehouse_code', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=10)),
                ('global_rate', models.FloatField(default=0)),
                ('max_cost', models.FloatField(default=0)),
                ('min_cost', models.FloatField(default=0)),
                ('max_price', models.FloatField(default=0)),
                ('min_price', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('factory_code', models.CharField(max_length=30, null=True)),
                ('purchaseorder_date', models.DateField(null=True)),
                ('purcaseorder_quantity', models.IntegerField(null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('purcase_quantity', models.IntegerField(null=True)),
                ('deposit_date', models.DateField(null=True)),
                ('deposit_price', models.FloatField(null=True)),
                ('dealer_code', models.CharField(max_length=30, null=True)),
                ('order_date', models.DateField(null=True)),
                ('order_quantity', models.IntegerField(null=True)),
                ('sale_date', models.DateField(null=True)),
                ('sale_quantity', models.IntegerField(null=True)),
                ('payment_date', models.DateField(null=True)),
                ('payment_price', models.FloatField(null=True)),
                ('parent_inventory', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('deposititem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit_slip.deposititem')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_slip.orderitem')),
                ('paymentitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_slip.paymentitem')),
                ('purcaseitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_slip.purchaseitem')),
                ('purchaseorderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder_slip.purchaseorderitem')),
                ('saleitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_slip.saleitem')),
            ],
        ),
    ]
