# Generated by Django 4.2.3 on 2023-08-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
