# Generated by Django 4.2.3 on 2023-08-29 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_slip', '0006_order_dealer_code'),
        ('purchaseorder_slip', '0002_purchaseorder_other'),
        ('deposit_slip', '0002_deposit_sale_no'),
        ('payment_slip', '0002_rename_dealer_code_payment_supplier_code'),
        ('sale_slip', '0004_sale_order_no'),
        ('purchase_slip', '0005_remove_purchase_dealer_code'),
        ('product_inventory', '0002_productinventory_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='deposititem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deposit_slip.deposititem'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_slip.orderitem'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='paymentitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_slip.paymentitem'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='purcaseitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_slip.purchaseitem'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='purchaseorderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseorder_slip.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='saleitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale_slip.saleitem'),
        ),
    ]
