# Generated by Django 4.2.3 on 2023-08-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory', '0003_alter_productinventory_deposititem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
