# Generated by Django 4.2.3 on 2023-09-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0005_rename_max_price_product_max_cost_and_more'),
        ('size_register', '0001_initial'),
        ('color_register', '0002_rename_color_code_color_code_and_more'),
        ('product_inventory', '0005_rename_purcase_quantity_productinventory_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinventory',
            old_name='purchaseitem',
            new_name='purchaseItem',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='saleitem',
            new_name='saleItem',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='dealer_code',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='deposit_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='deposit_price',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='deposititem',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='factory_code',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='global_rate',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='max_cost',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='min_cost',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='orderitem',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='parent_inventory',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='payment_price',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='paymentitem',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_part_number',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='purcaseorder_quantity',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='purchase_quantity',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='purchaseorder_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='purchaseorderitem',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='sale_quantity',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='size_code',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='storehouse_code',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='update_date',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='color_register.color'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='in_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='out_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_register.product'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='size_register.size'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='state',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
