# Generated by Django 4.2.3 on 2023-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder_slip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='other',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
