# Generated by Django 4.2.3 on 2023-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_slip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='sale_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
