# Generated by Django 4.2.3 on 2023-08-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment_slip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consignmentitem',
            old_name='order',
            new_name='consignment',
        ),
    ]
