# Generated by Django 4.2.3 on 2023-08-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment_slip', '0002_rename_order_consignmentitem_consignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='slip_date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
