# Generated by Django 4.2.3 on 2023-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment_slip', '0003_alter_consignment_slip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='other',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
