# Generated by Django 4.2.3 on 2023-08-01 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderslip',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderslip',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
