# Generated by Django 4.2.3 on 2023-08-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Item',
        ),
    ]
