# Generated by Django 4.2.3 on 2023-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_slip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cash_credit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
