# Generated by Django 4.2.3 on 2023-08-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_slip', '0002_alter_sale_cash_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dealer_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
