# Generated by Django 4.2.3 on 2023-09-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_slip', '0007_remove_orderitem_color_code_and_more'),
        ('product_register', '0005_rename_max_price_product_max_cost_and_more'),
        ('color_register', '0002_rename_color_code_color_code_and_more'),
        ('size_register', '0001_initial'),
        ('sale_slip', '0004_sale_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='max_cost',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='min_cost',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product_part_number',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='size_code',
        ),
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_slip.order'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='color_register.color'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_register.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='size_register.size'),
        ),
    ]
