# Generated by Django 4.2.3 on 2023-08-14 06:51

from django.db import migrations, models
import product_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0002_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(null=True, upload_to=product_register.models.generate_custom_filename),
        ),
    ]
