# Generated by Django 4.2.3 on 2023-08-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ancient_time',
            new_name='max_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='min_price',
        ),
    ]
