# Generated by Django 4.2.3 on 2023-08-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_register', '0004_rename_ancient_time_product_max_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_price',
            new_name='max_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_price',
            new_name='min_cost',
        ),
    ]
